<?php

namespace model\gmapi\proxy\__CG__\model\gmapi;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class GmapiLicensee extends \model\gmapi\GmapiLicensee implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'idLicensee', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'licenseeName', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'regulationNumber', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'contactPerson', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'contactEmail', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'configurationId', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'subcasinos', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'sceretKey', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'dbPrefix', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'url', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'winLimit', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'licenseeStatus', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'gameHistoryApiUrl', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'freeRound', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'fastSpeed', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'encode', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'transactionIdLength', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'roundIdLength', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'lastUpdated', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'gmapiConfiguration');
        }

        return array('__isInitialized__', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'idLicensee', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'licenseeName', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'regulationNumber', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'contactPerson', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'contactEmail', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'configurationId', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'subcasinos', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'sceretKey', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'dbPrefix', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'url', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'winLimit', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'licenseeStatus', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'gameHistoryApiUrl', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'freeRound', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'fastSpeed', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'encode', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'transactionIdLength', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'roundIdLength', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'lastUpdated', '' . "\0" . 'model\\gmapi\\GmapiLicensee' . "\0" . 'gmapiConfiguration');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (GmapiLicensee $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdLicensee()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdLicensee();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdLicensee', array());

        return parent::getIdLicensee();
    }

    /**
     * {@inheritDoc}
     */
    public function setLicenseeName($licenseeName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLicenseeName', array($licenseeName));

        return parent::setLicenseeName($licenseeName);
    }


    /**
     * {@inheritDoc}
     */
    public function getLicenseeName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLicenseeName', array());

        return parent::getLicenseeName();
    }

    /**
     * {@inheritDoc}
     */
    public function setRegulationNumber($regulationNumber)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRegulationNumber', array($regulationNumber));

        return parent::setRegulationNumber($regulationNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getRegulationNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRegulationNumber', array());

        return parent::getRegulationNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactPerson($contactPerson)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactPerson', array($contactPerson));

        return parent::setContactPerson($contactPerson);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactPerson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactPerson', array());

        return parent::getContactPerson();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactEmail($contactEmail)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactEmail', array($contactEmail));

        return parent::setContactEmail($contactEmail);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactEmail()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactEmail', array());

        return parent::getContactEmail();
    }

    /**
     * {@inheritDoc}
     */
    public function setConfigurationId($configurationId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setConfigurationId', array($configurationId));

        return parent::setConfigurationId($configurationId);
    }

    /**
     * {@inheritDoc}
     */
    public function getConfigurationId()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getConfigurationId', array());

        return parent::getConfigurationId();
    }

    /**
     * {@inheritDoc}
     */
    public function setSubcasinos($subcasinos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSubcasinos', array($subcasinos));

        return parent::setSubcasinos($subcasinos);
    }

    /**
     * {@inheritDoc}
     */
    public function getSubcasinos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSubcasinos', array());

        return parent::getSubcasinos();
    }

    /**
     * {@inheritDoc}
     */
    public function setSceretKey($sceretKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSceretKey', array($sceretKey));

        return parent::setSceretKey($sceretKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getSceretKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSceretKey', array());

        return parent::getSceretKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setDbPrefix($dbPrefix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDbPrefix', array($dbPrefix));

        return parent::setDbPrefix($dbPrefix);
    }

    /**
     * {@inheritDoc}
     */
    public function getDbPrefix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDbPrefix', array());

        return parent::getDbPrefix();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', array($url));

        return parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', array());

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setWinLimit($winLimit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWinLimit', array($winLimit));

        return parent::setWinLimit($winLimit);
    }

    /**
     * {@inheritDoc}
     */
    public function getWinLimit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWinLimit', array());

        return parent::getWinLimit();
    }

    /**
     * {@inheritDoc}
     */
    public function setLicenseeStatus($licenseeStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLicenseeStatus', array($licenseeStatus));

        return parent::setLicenseeStatus($licenseeStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getLicenseeStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLicenseeStatus', array());

        return parent::getLicenseeStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setGameHistoryApiUrl($gameHistoryApiUrl)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGameHistoryApiUrl', array($gameHistoryApiUrl));

        return parent::setGameHistoryApiUrl($gameHistoryApiUrl);
    }

    /**
     * {@inheritDoc}
     */
    public function getGameHistoryApiUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGameHistoryApiUrl', array());

        return parent::getGameHistoryApiUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setFreeRound($freeRound)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFreeRound', array($freeRound));

        return parent::setFreeRound($freeRound);
    }

    /**
     * {@inheritDoc}
     */
    public function getFreeRound()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFreeRound', array());

        return parent::getFreeRound();
    }

    /**
     * {@inheritDoc}
     */
    public function setFastSpeed($fastSpeed)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFastSpeed', array($fastSpeed));

        return parent::setFastSpeed($fastSpeed);
    }

    /**
     * {@inheritDoc}
     */
    public function getFastSpeed()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFastSpeed', array());

        return parent::getFastSpeed();
    }

    /**
     * {@inheritDoc}
     */
    public function setEncode($encode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEncode', array($encode));

        return parent::setEncode($encode);
    }

    /**
     * {@inheritDoc}
     */
    public function getEncode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEncode', array());

        return parent::getEncode();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransactionIdLength($transactionIdLength)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransactionIdLength', array($transactionIdLength));

        return parent::setTransactionIdLength($transactionIdLength);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransactionIdLength()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransactionIdLength', array());

        return parent::getTransactionIdLength();
    }

    /**
     * {@inheritDoc}
     */
    public function setRoundIdLength($roundIdLength)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRoundIdLength', array($roundIdLength));

        return parent::setRoundIdLength($roundIdLength);
    }

    /**
     * {@inheritDoc}
     */
    public function getRoundIdLength()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRoundIdLength', array());

        return parent::getRoundIdLength();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastUpdated($lastUpdated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastUpdated', array($lastUpdated));

        return parent::setLastUpdated($lastUpdated);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastUpdated', array());

        return parent::getLastUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setGmapiConfiguration(\model\gmapi\GmapiConfiguration $gmapiConfiguration = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGmapiConfiguration', array($gmapiConfiguration));

        return parent::setGmapiConfiguration($gmapiConfiguration);
    }

    /**
     * {@inheritDoc}
     */
    public function getGmapiConfiguration()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGmapiConfiguration', array());

        return parent::getGmapiConfiguration();
    }

}
